[global]
disable_modifier_guard = 1

[ids]
*

[main]
# When tapped, emit Right Alt. When held, activate the custom layer.
rightalt = overload(rightalt_layer, rightalt)

# Copilot to Ctrl
f23 = rightcontrol
# Swallow Super+Shift+F23 combo so only Ctrl comes through
leftmeta+leftshift+f23 = rightcontrol

# Define the custom layer. 
# The ":G" tells keyd to apply the AltGr (Right Alt) modifier to 
# any key NOT explicitly mapped in this block. 
[rightalt_layer:A]
[ = home
] = end

